version: '3.2'
services:
  regiu:
    image: "regiu:1.5"
    ports:
      - "80:80"
    volumes:
      - /giu/chamberlain/books:/usr/share/nginx/html/books
    networks:
      - regiu-network
    depends_on:
      - chamberlain
  chamberlain:
    image: "chamberlain:1.7"
    ports:
      - "8080:8080"
    volumes:
      - /var:/var
      - /usr/bin/git:/usr/bin/git
      - /usr/bin/ssh:/usr/bin/ssh
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - /usr/share/git-core/templates:/usr/share/git-core/templates
      - /giu/chamberlain/books:/giu/chamberlain/books
    networks:
      - regiu-network
    depends_on:
      - database
  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - /giu/chamberlain/database:/var/lib/mysql 
      - /giu/chamberlain/database:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "199527"
    networks:
      - regiu-network
networks:
  regiu-network:
    driver: overlay
