version: '3.2'
services:
  regiu:
    image: "swr.cn-east-3.myhuaweicloud.com/coregiu/regiu:1.0.0"
    ports:
      - "80:80"
    networks:
      - regiu-network
    depends_on:
      - chamberlain
  chamberlain:
    image: "swr.cn-east-3.myhuaweicloud.com/coregiu/chamberlain:1.0.0"
    ports:
      - "8080:8080"
    volumes:
      - /var:/var
      - /opt/chamberlain/runtime/chamberlain.yml:/chamberlain.yml
    networks:
      - regiu-network
    depends_on:
      - database
  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - /giu/chamberlain/database:/var/lib/mysql 
      - /giu/chamberlain/database:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - regiu-network
networks:
  regiu-network:
    driver: overlay
